src/Entity/Country.php
<?php

namespace App\Entity;

use App\Repository\CountryRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CountryRepository::class)
 */
class Country
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $capital;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $flag;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCapital(): ?string
    {
        return $this->capital;
    }

    public function setCapital(string $capital): self
    {
        $this->capital = $capital;

        return $this;
    }

    public function getFlag(): ?string
    {
        return $this->flag;
    }

    public function setFlag(string $flag): self
    {
        $this->flag = $flag;

        return $this;
    }
}

src/Entity/Result.php
<?php

namespace App\Entity;

use App\Repository\ResultRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * @ORM\Entity(repositoryClass=ResultRepository::class)
 */
class Result
{
    public function __construct(){
        $this->date = new \DateTime("now");

    }
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="integer")
     */
    private $correct_answer;

    /**
     * @ORM\Column(type="integer")
     */
    private $not_correct_answer;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getCorrectAnswer(): ?int
    {
        return $this->correct_answer;
    }

    public function setCorrectAnswer(int $correct_answer): self
    {
        $this->correct_answer = $correct_answer;

        return $this;
    }

    public function getNotCorrectAnswer(): ?int
    {
        return $this->not_correct_answer;
    }

    public function setNotCorrectAnswer(int $not_correct_answer): self
    {
        $this->not_correct_answer = $not_correct_answer;

        return $this;
    }
}

src/Controller/HomepageController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class HomepageController extends AbstractController
{

    /**
     * @Route("/", name="homepage", methods={"GET"})
     */
    public function homepage()
    {
        return $this->render('homepage.html.twig');

    }



}

src/Controller/QuizController.php
<?php

namespace App\Controller;

use App\Entity\Country;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;


class QuizController extends AbstractController
{
    /**
     * @Route("/quiz", name="quiz")
     */
    public function start(ManagerRegistry $doctrine)
    {
        $all_countries = $doctrine->getRepository(Country::class)->findAll();
        shuffle($all_countries);
        $quiz_countries = array_slice($all_countries, 0, 5);

        return $this->render('quiz.html.twig', [
            'countries' => $quiz_countries
        ]);

    }

}

src/Controller/ResultController.php
<?php

namespace App\Controller;

use App\Entity\Result;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class ResultController extends AbstractController
{

    /**
     * @Route("/save-results", name="save-results", methods={"POST"})
     */
    public function save(ManagerRegistry $doctrine, Request $request)
    {

        $entityManager = $doctrine->getManager();

        $correct_answers = $request->request->get('correct_answers');
        $bad_answers = $request->request->get('bad_answers');

        $result = new Result();
        $result->setCorrectAnswer($correct_answers);
        $result->setNotCorrectAnswer($bad_answers);

        $entityManager->persist($result);
        $entityManager->flush();

        return $this->render('homepage.html.twig', [
            'bad_answers' => $bad_answers,
            'correct_answers' => $correct_answers
        ]);
    }


    /**
     * @Route("/show-results", name="show-results", methods={"GET"})
     */
    public function show(ManagerRegistry $doctrine)
    {
        $results = $doctrine->getRepository(Result::class)->findAll();

        return $this->render('results.html.twig', [
            'results' => $results
        ]);

    }

}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}
        {% block jsuites %}
            <script src="https://jsuites.net/v4/jsuites.js"></script>
            <link rel="stylesheet" href="https://jsuites.net/v4/jsuites.css" type="text/css" />
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
            {% endblock %}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    </head>
    <body>
        {% block body %} {% endblock %}
    </body>
</html>

templates/homepage.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<div class="mt-5">
    {% if correct_answers is defined %}
            <div class="d-flex justify-content-center font-weight-bold">Prawidłowych odpowiedzi: {{ correct_answers }}</div>
            <div class="d-flex justify-content-center font-weight-bold">Błędnych odpowiedzi: {{ bad_answers }}</div>

        <ul class="nav justify-content-center">
            <li class="nav-item">
                <a class="nav-link active  btn-primary" href="{{ path('quiz') }}">Spróbuj jeszcze raz</a>
            </li>
        </ul>
        {% else %}
            <ul class="nav justify-content-center">
                <li class="nav-item">
                    <a class="nav-link active" href="{{ path('quiz') }}">Start</a>
                </li>
            </ul>
    {% endif %}
    <ul class="nav justify-content-center">
        <li class="nav-item">
            <a class="nav-link active" href="{{ path('show-results') }}">Historia rezultatów</a>
        </li>
    </ul>
</div>
{% endblock %}

templates/quiz.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="d-block mx-auto mt-4 text-center" style="width: 300px">
    {% set quiz_variant = random(['quess_country', 'quess_capital']) %}
    {% if quiz_variant == 'quess_country' %}
        <div class="font-weight-bold text-center">Do jakiego Państwa należy ta flaga?</div>
    {% else %}
        <div class="font-weight-bold mx-auto text-center">Podaj stolicę danego Państwa</div>
    {% endif %}

{% for country in countries %}
    {% if loop.index == '1' %}
    <div data-number="{{ loop.index }}" class="active_question">
    {% if quiz_variant == 'quess_country' %}
        <div class="d-block m-3"><img alt="flag" width="200" height="150" src="build/images/{{ country.flag }}"></div>
    {% else %}
        <div class="d-block text-center m-3">{{ country.name }}</div>
    {% endif %}
        <div class="text-center m-2">
        <form id="user-answer-form">
            <input  type="text" id="user-answer">
        </form>
        </div>
            <button class="check_answer btn btn-primary btn-sm">Sprawdź</button>
    {% if quiz_variant == 'quess_country' %}
        <div id="correct-answer" hidden class="m-2 font-weight-bold">{{ country.name }}</div>
    {% else %}
        <div id="correct-answer" hidden class="m-2 font-weight-bold">{{ country.capital }}</div>
    {% endif %}
        <div id="correct_butt" hidden class="m-2"><button class="btn btn-success btn-sm">Poprawnie</button></div>
        <div id="not_correct_butt" hidden class="m-2"><button class="btn btn-outline-danger btn-sm">Niepoprawnie</button></div>
        <button id="next_butt" hidden data-number="{{ loop.index }}" class="btn btn-dark btn-sm">Następne pytanie</button>
    </div>
        {% elseif loop.last %}
            <div data-number="{{ loop.index }}" class="hidden">
                {% if quiz_variant == 'quess_country' %}
                    <div class="d-block m-3"><img alt="flag" width="200" height="150" src="build/images/{{ country.flag }}"></div>
                {% else %}
                    <div class="d-block text-center m-3">{{ country.name }}</div>
                {% endif %}
                <div class="text-center m-2">
                <form id="user-answer-form">
                    <input type="text" id="user-answer">
                </form>
                </div>
                    <button class="check_answer btn btn-primary btn-sm">Sprawdź</button>
                {% if quiz_variant == 'quess_country' %}
                    <div id="correct-answer" hidden class="m-2 font-weight-bold">{{ country.name }}</div>
                {% else %}
                    <div id="correct-answer" hidden class="m-2 font-weight-bold">{{ country.capital }}</div>
                {% endif %}
                <div id="correct_butt" hidden class="m-2"><button class="btn btn-success btn-sm">Poprawnie</button></div>
                <div id="not_correct_butt" hidden class="m-2"><button class="btn btn-outline-danger btn-sm">Niepoprawnie</button></div>
                <form method="post" action="/save-results" id="summary_form" name="results" hidden>
                    <input type="number" id="correct_answers_counter" name="correct_answers" value=0><br><br>
                    <input type="number" id="bad_answers_counter" name="bad_answers" value=0><br><br>
                    <input type="submit" value="Submit">
                </form>
                <div id="summary" class="hidden">
                    Poprawnych odpowiedzi: <span id="correct"></span><br><br>
                    Błędnych odpowiedzi: <span id="not_correct"></span><br><br>
                </div>
            </div>
    {% else %}
        <div data-number="{{ loop.index }}" class="hidden">
            {% if quiz_variant == 'quess_country' %}
                <div class="d-block m-3"><img alt="flag" width="200" height="150" src="build/images/{{ country.flag }}"></div>
            {% else %}
                <div class="d-block text-center m-3">{{ country.name }}</div>
            {% endif %}
            <div class="text-center m-2">
            <form id="user-answer-form">
                <input type="text" id="user-answer">
            </form>
            </div>
                <button class="check_answer btn btn-primary btn-sm" data-number="{{ loop.index }}">Sprawdź</button>
            {% if quiz_variant == 'quess_country' %}
                <div id="correct-answer" hidden class="m-2 font-weight-bold">{{ country.name }}</div>
            {% else %}
                <div id="correct-answer" hidden class="m-2 font-weight-bold">{{ country.capital }}</div>
            {% endif %}
            <div id="correct_butt" hidden class="m-2"><button class="btn btn-success btn-sm">Poprawnie</button></div>
            <div id="not_correct_butt" hidden class="m-2"><button class="btn btn-outline-danger btn-sm">Niepoprawnie</button></div>
            <button id="next_butt" hidden data-number="{{ loop.index }}" class="btn btn-dark btn-sm">Następne pytanie</button>
        </div>
        {% endif %}
    {% endfor %}
    <div id="ajax"></div>
</div>
{% endblock %}

templates/results.html.twig
{% extends 'base.html.twig' %}
{% block jsuites %}
<script src="https://jsuites.net/v4/jsuites.js"></script>
<link rel="stylesheet" href="https://jsuites.net/v4/jsuites.css" type="text/css" />
{% endblock %}

{% block body %}
    <div class="m-3">
    <div class="mx-auto" style="width: 300px"><h1>Wyniki quizu</h1></div>
    <p>Wybierz zakres dat</p>
    <div>Od: </div><input id='calendar'> <div>Do: </div><input id='calendar2'><br>
    <div id="from_date" hidden></div>
    <div id="until_date" hidden></div>
    <table class="table table-sm table-striped">
        <thead class="thead-dark">
        <th scope="col">#</th><th scope="col">Data</th><th scope="col">Poprawne odpowiedzi</th><th scope="col">Błędne odpowiedzi</th>
        </thead>
        {% for result in results %}
            <tr class="">
                <th scope="row">{{ loop.index }}</th><td id="date">{{ result.date|format_datetime(pattern="Y-MM-dd H:mm:ss") }}</td><td>{{ result.correctAnswer }}</td><td>{{ result.notCorrectAnswer }}</td>
            </tr>
        {% endfor %}
    </table>
    <ul class="nav justify-content-center">
        <li class="nav-item">
            <a class="nav-link active" href="{{ path('homepage') }}">Strona startowa</a>
        </li>
    </ul>
    </div>
{% endblock %}